apiVersion: apps/v1
kind: Deployment
metadata:
  name: buggyapp-deployment
spec:
  selector:
    matchLabels:
      app: buggyapp
  template:
    metadata:
      labels:
        app: buggyapp
    spec:
      containers:
      - name: buggycontainer
        image: 008971657113.dkr.ecr.ap-south-1.amazonaws.com/devsecops:latest
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: buggyapp_service
spec:
  selector:
    app: buggyapp
  ports:
    - name: http 
      port: 80
      protocol: TCP
      targetPort: 8080 
  type: LoadBalancer

